// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/generate_cpv_ts.js
// Source: Supabase (cpv_codes table) - DIVISIONS ONLY

// Map of 2-digit prefix to Division Name (EN)
export const CPV_DIVISION_MAP: Record<string, string> = {
  "14": "Mining, basic metals and related products",
  "15": "Food, beverages, tobacco and related products",
  "16": "Agricultural machinery",
  "18": "Clothing, footwear, luggage articles and accessories",
  "19": "Leather and textile fabrics, plastic and rubber materials",
  "22": "Printed matter and related products",
  "24": "Chemical products",
  "30": "Office and computing machinery, equipment and supplies except furniture and software packages",
  "31": "Electrical machinery, apparatus, equipment and consumables; lighting",
  "32": "Radio, television, communication, telecommunication and related equipment",
  "33": "Medical equipments, pharmaceuticals and personal care products",
  "34": "Transport equipment and auxiliary products to transportation",
  "35": "Security, fire-fighting, police and defence equipment",
  "37": "Musical instruments, sport goods, games, toys, handicraft, art materials and accessories",
  "38": "Laboratory, optical and precision equipments (excl. glasses)",
  "39": "Furniture (incl. office furniture), furnishings, domestic appliances (excl. lighting) and cleaning products",
  "41": "Collected and purified water",
  "42": "Industrial machinery",
  "43": "Machinery for mining, quarrying, construction equipment",
  "44": "Construction structures and materials; auxiliary products to construction (except electric apparatus)",
  "45": "Construction work",
  "48": "Software package and information systems",
  "50": "Repair and maintenance services",
  "51": "Installation services (except software)",
  "55": "Hotel, restaurant and retail trade services",
  "60": "Transport services (excl. Waste transport)",
  "63": "Supporting and auxiliary transport services; travel agencies services",
  "64": "Postal and telecommunications services",
  "65": "Public utilities",
  "66": "Financial and insurance services",
  "70": "Real estate services",
  "71": "Architectural, construction, engineering and inspection services",
  "72": "IT services: consulting, software development, Internet and support",
  "73": "Research and development services and related consultancy services",
  "75": "Administration, defence and social security services",
  "76": "Services related to the oil and gas industry",
  "77": "Agricultural, forestry, horticultural, aquacultural and apicultural services",
  "79": "Business services: law, marketing, consulting, recruitment, printing and security",
  "80": "Education and training services",
  "85": "Health and social work services",
  "90": "Sewage, refuse, cleaning and environmental services",
  "92": "Recreational, cultural and sporting services",
  "98": "Other community, social and personal services",
  "03": "Agricultural, farming, fishing, forestry and related products",
  "09": "Petroleum products, fuel, electricity and other sources of energy"
};

// Map of 2-digit prefix to Division Name (PT)
export const CPV_DIVISION_MAP_PT: Record<string, string> = {
  "14": "Exploração mineira, metais de base e produtos afins",
  "15": "Produtos alimentares, bebidas, tabaco e produtos afins",
  "16": "Maquinaria agrícola",
  "18": "Vestuário, calçado, malas e artigos de viagem, acessórios",
  "19": "Materiais têxteis, de couro, de plástico e de borracha",
  "22": "Material impresso e afins",
  "24": "Produtos químicos",
  "30": "Máquinas, equipamento e material de escritório e de informática, excepto mobiliário e pacotes de programas (software)",
  "31": "Maquinaria, aparelhagem, equipamento e consumíveis eléctricos; iluminação",
  "32": "Equipamento de rádio, televisão, comunicação, telecomunicações e afins",
  "33": "Equipamento médico, medicamentos e produtos para cuidados pessoais",
  "34": "Equipamento e produtos auxiliares de transporte",
  "35": "Equipamento de segurança, combate a incêndios, polícia e defesa",
  "37": "Instrumentos musicais, artigos de desporto, jogos, brinquedos, material para artesanato e actividades artísticas e acessórios",
  "38": "Equipamento laboratorial, óptico e de precisão (exc. óculos)",
  "39": "Mobiliário (incl. de escritório), acessórios, aparelhos domésticos (excl. iluminação) e produtos de limpeza",
  "41": "Água captada e tratada",
  "42": "Máquinas industriais",
  "43": "Maquinaria para extracção mineira e pedreiras, equipamento de construção",
  "44": "Estruturas e materiais de construção; produtos auxiliares de construção (excepto aparelhos eléctricos)",
  "45": "Construção",
  "48": "Pacotes de software e sistemas de informação",
  "50": "Serviços de reparação e manutenção",
  "51": "Serviços de instalação (excepto software)",
  "55": "Serviços de hotelaria, restauração e comércio a retalho",
  "60": "Serviços de transporte (excl. transporte de resíduos)",
  "63": "Serviços anexos e auxiliares dos transportes; serviços de agências de viagens",
  "64": "Serviços postais e de telecomunicações",
  "65": "Serviços públicos",
  "66": "Serviços de finanças e seguros",
  "70": "Serviços imobiliários",
  "71": "Serviços de arquitectura, construção, engenharia e inspecção",
  "72": "Serviços de TI: consultoria, desenvolvimento de software, Internet e apoio",
  "73": "Serviços de investigação e desenvolvimento e serviços de consultoria conexos",
  "75": "Serviços relacionados com a administração pública, a defesa e a segurança social",
  "76": "Serviços relacionados com as indústrias do gás e do petróleo",
  "77": "Serviços de agricultura, silvicultura, horticultura, aquicultura e apicultura",
  "79": "Serviços a empresas: direito, comercialização, consultoria, recrutamento, impressão e segurança",
  "80": "Serviços de ensino e formação",
  "85": "Serviços de saúde e acção social",
  "90": "Serviços relativos a águas residuais, resíduos, limpeza e ambiente",
  "92": "Serviços recreativos, culturais e desportivos",
  "98": "Outros serviços comunitários, sociais e pessoais",
  "03": "Produtos da agricultura, da pesca, da silvicultura e afins",
  "09": "Produtos petrolíferos, combustíveis, electricidade e outras fontes de energia"
};

// Array for Dropdowns
export const CPV_DIVISIONS = [
  {
    "value": "03",
    "label": "Agricultural, farming, fishing, forestry and related products",
    "label_pt": "Produtos da agricultura, da pesca, da silvicultura e afins",
    "fullCode": "03000000"
  },
  {
    "value": "09",
    "label": "Petroleum products, fuel, electricity and other sources of energy",
    "label_pt": "Produtos petrolíferos, combustíveis, electricidade e outras fontes de energia",
    "fullCode": "09000000"
  },
  {
    "value": "14",
    "label": "Mining, basic metals and related products",
    "label_pt": "Exploração mineira, metais de base e produtos afins",
    "fullCode": "14000000"
  },
  {
    "value": "15",
    "label": "Food, beverages, tobacco and related products",
    "label_pt": "Produtos alimentares, bebidas, tabaco e produtos afins",
    "fullCode": "15000000"
  },
  {
    "value": "16",
    "label": "Agricultural machinery",
    "label_pt": "Maquinaria agrícola",
    "fullCode": "16000000"
  },
  {
    "value": "18",
    "label": "Clothing, footwear, luggage articles and accessories",
    "label_pt": "Vestuário, calçado, malas e artigos de viagem, acessórios",
    "fullCode": "18000000"
  },
  {
    "value": "19",
    "label": "Leather and textile fabrics, plastic and rubber materials",
    "label_pt": "Materiais têxteis, de couro, de plástico e de borracha",
    "fullCode": "19000000"
  },
  {
    "value": "22",
    "label": "Printed matter and related products",
    "label_pt": "Material impresso e afins",
    "fullCode": "22000000"
  },
  {
    "value": "24",
    "label": "Chemical products",
    "label_pt": "Produtos químicos",
    "fullCode": "24000000"
  },
  {
    "value": "30",
    "label": "Office and computing machinery, equipment and supplies except furniture and software packages",
    "label_pt": "Máquinas, equipamento e material de escritório e de informática, excepto mobiliário e pacotes de programas (software)",
    "fullCode": "30000000"
  },
  {
    "value": "31",
    "label": "Electrical machinery, apparatus, equipment and consumables; lighting",
    "label_pt": "Maquinaria, aparelhagem, equipamento e consumíveis eléctricos; iluminação",
    "fullCode": "31000000"
  },
  {
    "value": "32",
    "label": "Radio, television, communication, telecommunication and related equipment",
    "label_pt": "Equipamento de rádio, televisão, comunicação, telecomunicações e afins",
    "fullCode": "32000000"
  },
  {
    "value": "33",
    "label": "Medical equipments, pharmaceuticals and personal care products",
    "label_pt": "Equipamento médico, medicamentos e produtos para cuidados pessoais",
    "fullCode": "33000000"
  },
  {
    "value": "34",
    "label": "Transport equipment and auxiliary products to transportation",
    "label_pt": "Equipamento e produtos auxiliares de transporte",
    "fullCode": "34000000"
  },
  {
    "value": "35",
    "label": "Security, fire-fighting, police and defence equipment",
    "label_pt": "Equipamento de segurança, combate a incêndios, polícia e defesa",
    "fullCode": "35000000"
  },
  {
    "value": "37",
    "label": "Musical instruments, sport goods, games, toys, handicraft, art materials and accessories",
    "label_pt": "Instrumentos musicais, artigos de desporto, jogos, brinquedos, material para artesanato e actividades artísticas e acessórios",
    "fullCode": "37000000"
  },
  {
    "value": "38",
    "label": "Laboratory, optical and precision equipments (excl. glasses)",
    "label_pt": "Equipamento laboratorial, óptico e de precisão (exc. óculos)",
    "fullCode": "38000000"
  },
  {
    "value": "39",
    "label": "Furniture (incl. office furniture), furnishings, domestic appliances (excl. lighting) and cleaning products",
    "label_pt": "Mobiliário (incl. de escritório), acessórios, aparelhos domésticos (excl. iluminação) e produtos de limpeza",
    "fullCode": "39000000"
  },
  {
    "value": "41",
    "label": "Collected and purified water",
    "label_pt": "Água captada e tratada",
    "fullCode": "41000000"
  },
  {
    "value": "42",
    "label": "Industrial machinery",
    "label_pt": "Máquinas industriais",
    "fullCode": "42000000"
  },
  {
    "value": "43",
    "label": "Machinery for mining, quarrying, construction equipment",
    "label_pt": "Maquinaria para extracção mineira e pedreiras, equipamento de construção",
    "fullCode": "43000000"
  },
  {
    "value": "44",
    "label": "Construction structures and materials; auxiliary products to construction (except electric apparatus)",
    "label_pt": "Estruturas e materiais de construção; produtos auxiliares de construção (excepto aparelhos eléctricos)",
    "fullCode": "44000000"
  },
  {
    "value": "45",
    "label": "Construction work",
    "label_pt": "Construção",
    "fullCode": "45000000"
  },
  {
    "value": "48",
    "label": "Software package and information systems",
    "label_pt": "Pacotes de software e sistemas de informação",
    "fullCode": "48000000"
  },
  {
    "value": "50",
    "label": "Repair and maintenance services",
    "label_pt": "Serviços de reparação e manutenção",
    "fullCode": "50000000"
  },
  {
    "value": "51",
    "label": "Installation services (except software)",
    "label_pt": "Serviços de instalação (excepto software)",
    "fullCode": "51000000"
  },
  {
    "value": "55",
    "label": "Hotel, restaurant and retail trade services",
    "label_pt": "Serviços de hotelaria, restauração e comércio a retalho",
    "fullCode": "55000000"
  },
  {
    "value": "60",
    "label": "Transport services (excl. Waste transport)",
    "label_pt": "Serviços de transporte (excl. transporte de resíduos)",
    "fullCode": "60000000"
  },
  {
    "value": "63",
    "label": "Supporting and auxiliary transport services; travel agencies services",
    "label_pt": "Serviços anexos e auxiliares dos transportes; serviços de agências de viagens",
    "fullCode": "63000000"
  },
  {
    "value": "64",
    "label": "Postal and telecommunications services",
    "label_pt": "Serviços postais e de telecomunicações",
    "fullCode": "64000000"
  },
  {
    "value": "65",
    "label": "Public utilities",
    "label_pt": "Serviços públicos",
    "fullCode": "65000000"
  },
  {
    "value": "66",
    "label": "Financial and insurance services",
    "label_pt": "Serviços de finanças e seguros",
    "fullCode": "66000000"
  },
  {
    "value": "70",
    "label": "Real estate services",
    "label_pt": "Serviços imobiliários",
    "fullCode": "70000000"
  },
  {
    "value": "71",
    "label": "Architectural, construction, engineering and inspection services",
    "label_pt": "Serviços de arquitectura, construção, engenharia e inspecção",
    "fullCode": "71000000"
  },
  {
    "value": "72",
    "label": "IT services: consulting, software development, Internet and support",
    "label_pt": "Serviços de TI: consultoria, desenvolvimento de software, Internet e apoio",
    "fullCode": "72000000"
  },
  {
    "value": "73",
    "label": "Research and development services and related consultancy services",
    "label_pt": "Serviços de investigação e desenvolvimento e serviços de consultoria conexos",
    "fullCode": "73000000"
  },
  {
    "value": "75",
    "label": "Administration, defence and social security services",
    "label_pt": "Serviços relacionados com a administração pública, a defesa e a segurança social",
    "fullCode": "75000000"
  },
  {
    "value": "76",
    "label": "Services related to the oil and gas industry",
    "label_pt": "Serviços relacionados com as indústrias do gás e do petróleo",
    "fullCode": "76000000"
  },
  {
    "value": "77",
    "label": "Agricultural, forestry, horticultural, aquacultural and apicultural services",
    "label_pt": "Serviços de agricultura, silvicultura, horticultura, aquicultura e apicultura",
    "fullCode": "77000000"
  },
  {
    "value": "79",
    "label": "Business services: law, marketing, consulting, recruitment, printing and security",
    "label_pt": "Serviços a empresas: direito, comercialização, consultoria, recrutamento, impressão e segurança",
    "fullCode": "79000000"
  },
  {
    "value": "80",
    "label": "Education and training services",
    "label_pt": "Serviços de ensino e formação",
    "fullCode": "80000000"
  },
  {
    "value": "85",
    "label": "Health and social work services",
    "label_pt": "Serviços de saúde e acção social",
    "fullCode": "85000000"
  },
  {
    "value": "90",
    "label": "Sewage, refuse, cleaning and environmental services",
    "label_pt": "Serviços relativos a águas residuais, resíduos, limpeza e ambiente",
    "fullCode": "90000000"
  },
  {
    "value": "92",
    "label": "Recreational, cultural and sporting services",
    "label_pt": "Serviços recreativos, culturais e desportivos",
    "fullCode": "92000000"
  },
  {
    "value": "98",
    "label": "Other community, social and personal services",
    "label_pt": "Outros serviços comunitários, sociais e pessoais",
    "fullCode": "98000000"
  }
];

// For backward compatibility with some components
export const CPV_CODES = CPV_DIVISIONS; 

export function getCpvDescription(cpvCode: string | null | undefined, locale: string = 'en'): string {
    if (!cpvCode) return 'N/A';
    
    // Clean code
    const cleanCode = cpvCode.replace(/[^0-9]/g, '').slice(0, 8);
    const division = cleanCode.substring(0, 2);
    const map = locale === 'pt' ? CPV_DIVISION_MAP_PT : CPV_DIVISION_MAP;
    
    // If it is a division root
    if (cleanCode.endsWith('000000') && map[division]) {
        return map[division];
    }
    
    // If we have the parent category
    if (map[division]) {
        return map[division] + (locale === 'pt' ? ' (Categoria)' : ' (Category)');
    }
    
    return (locale === 'pt' ? 'Setor Especializado (' : 'Specialized Sector (') + cpvCode + ')';
}