import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'
import type { Metadata } from 'next'

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params
  return {
    title: 'Terms and Conditions',
    description: 'Terms and conditions for using the Winly procurement intelligence platform.',
    alternates: {
      canonical: `https://winly.me/${locale}/terms`,
      languages: { en: 'https://winly.me/en/terms', pt: 'https://winly.me/pt/terms' },
    },
  }
}

export default function TermsPage() {
  return (
    <div className="bg-zinc-50 min-h-screen font-sans text-zinc-900">
      <Navbar />

      <main className="pt-32 pb-20 px-6">
        <div className="max-w-3xl mx-auto bg-white p-10 rounded-3xl border border-zinc-200 shadow-sm">
          <h1 className="text-3xl font-black mb-2">Terms and Conditions</h1>
          <p className="text-zinc-500 mb-8">Last updated: March 31, 2026</p>

          <div className="prose prose-slate max-w-none">
            <h3>1. Introduction and Acceptance</h3>
            <p>
              These Terms and Conditions (&quot;Terms&quot;) govern your access to and use of the Winly platform, operated by Winly, Lda., a company registered in Portugal with its registered office at Avenida da Liberdade, 110, 1250-146 Lisboa, Portugal (&quot;Winly&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
            </p>
            <p>
              By creating an account, subscribing to a plan, or otherwise accessing or using the Winly platform, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you must not use the platform.
            </p>
            <p>
              These Terms apply in addition to our <a href="/privacy">Privacy Policy</a>, which describes how we collect and process your personal data.
            </p>

            <h3>2. Definitions</h3>
            <p>Throughout these Terms, the following definitions apply:</p>
            <ul>
              <li><strong>Platform</strong> — The Winly web application, APIs, and all related services accessible at winly.me.</li>
              <li><strong>User</strong> — Any individual or legal entity that accesses or uses the Platform, whether on a free or paid plan.</li>
              <li><strong>Account</strong> — The personal or organizational profile a User creates to access the Platform.</li>
              <li><strong>Services</strong> — All features provided by the Platform, including tender data aggregation, AI-powered analysis, document processing, matching, and procurement intelligence tools.</li>
              <li><strong>Content</strong> — All information, data, text, graphics, and other materials displayed on or generated by the Platform.</li>
              <li><strong>AI Output</strong> — Any analysis, recommendation, risk assessment, win probability estimate, or other result generated by the Platform&apos;s artificial intelligence systems.</li>
              <li><strong>Subscription</strong> — A recurring agreement under which a User pays for access to a paid tier of the Services.</li>
            </ul>

            <h3>3. Service Description</h3>
            <p>
              Winly is a procurement intelligence platform designed to help businesses find, evaluate, and compete for public contracts. The Platform provides the following capabilities:
            </p>
            <ul>
              <li>Aggregation of public tender data from official European (Tenders Electronic Daily — TED) and Portuguese (BASE) procurement sources.</li>
              <li>AI-powered analysis of tender documents, including risk assessment, requirement extraction, and opportunity evaluation.</li>
              <li>Intelligent matching of tenders to User profiles based on company capabilities, past performance, and sector alignment.</li>
              <li>Buyer intelligence, historical award data, and market analytics to support bid/no-bid decisions.</li>
              <li>AI-assisted chat for exploring tender details and procurement questions.</li>
            </ul>
            <p>
              The data displayed on the Platform originates from publicly available sources. Winly processes, enriches, and presents this data but does not create or control the underlying public records.
            </p>

            <h3>4. Account Registration</h3>
            <p>
              To use certain features of the Platform, you must create an Account. When registering, you agree to:
            </p>
            <ul>
              <li>Provide accurate, current, and complete information during the registration process.</li>
              <li>Maintain and promptly update your Account information to keep it accurate and complete.</li>
              <li>Maintain only one Account per individual person. Creating multiple accounts to circumvent plan limits or for any other purpose is prohibited.</li>
              <li>Keep your login credentials secure and confidential. You are fully responsible for all activity that occurs under your Account.</li>
              <li>Notify us immediately at <a href="mailto:support.winly@winly.me">support.winly@winly.me</a> if you suspect any unauthorized access to your Account.</li>
            </ul>
            <p>
              You must be at least 18 years of age to create an Account and use the Platform. By registering, you confirm that you meet this requirement.
            </p>

            <h3>5. Subscription Plans and Billing</h3>
            <p>
              Winly offers the following subscription tiers:
            </p>
            <ul>
              <li><strong>Explorer (Free)</strong> — Limited access to the Platform at no charge.</li>
              <li><strong>Pro</strong> — &euro;99 per month, or &euro;79 per month when billed annually.</li>
              <li><strong>Enterprise</strong> — &euro;199 per month, or &euro;159 per month when billed annually.</li>
            </ul>
            <p>
              All prices are in euros and include applicable taxes unless otherwise stated. Paid Subscriptions are billed in advance on a monthly or annual basis, depending on the billing cycle you select.
            </p>
            <p>
              Subscriptions automatically renew at the end of each billing period unless you cancel before the renewal date. You authorize us to charge the payment method on file for each renewal period.
            </p>
            <p>
              All payments are processed securely by our payment partner, Lemon Squeezy (Lemon Squeezy, LLC). By subscribing, you also agree to Lemon Squeezy&apos;s terms of service. Winly does not store your full payment card details.
            </p>
            <p>
              We reserve the right to change our pricing. If we do, we will provide at least 30 days&apos; advance notice by email before the new price takes effect. The updated price will apply from your next billing cycle after the notice period.
            </p>

            <h3>6. Cancellation and Refunds</h3>
            <p>
              You may cancel your Subscription at any time through your Account settings. Upon cancellation:
            </p>
            <ul>
              <li>Your Subscription will remain active until the end of the current billing period.</li>
              <li>You will not be charged for subsequent billing periods.</li>
              <li>Your Account will revert to the Explorer (Free) tier at the end of the paid period.</li>
            </ul>
            <p>
              In accordance with the EU Consumer Rights Directive (Directive 2011/83/EU), if you are a consumer residing in the European Union, you have the right to withdraw from a new Subscription within 14 days of purchase without giving any reason. To exercise this right, contact us at <a href="mailto:support.winly@winly.me">support.winly@winly.me</a> with a clear statement of your decision to withdraw. If you have used the Services during the cooling-off period, we may deduct a proportional amount for the period of use.
            </p>
            <p>
              After the 14-day cooling-off period has elapsed, Subscriptions are non-refundable for the current billing period.
            </p>

            <h3>7. Acceptable Use</h3>
            <p>
              You agree to use the Platform only for its intended purpose and in compliance with all applicable laws. The following activities are strictly prohibited:
            </p>
            <ul>
              <li>Scraping, crawling, or using automated tools to extract data from the Platform beyond the functionality provided by your Subscription tier.</li>
              <li>Reselling, redistributing, sublicensing, or commercially exploiting Platform data or AI Outputs to third parties.</li>
              <li>Using bots, scripts, or other automated means to access the Platform, submit requests, or circumvent rate limits.</li>
              <li>Reverse engineering, decompiling, or disassembling any part of the Platform, its algorithms, or its source code.</li>
              <li>Sharing your Account credentials with others or allowing third parties to access the Platform through your Account.</li>
              <li>Using the Platform to facilitate any illegal activity, including but not limited to fraud, bid-rigging, or corruption in public procurement.</li>
              <li>Attempting to interfere with the Platform&apos;s infrastructure, security, or availability.</li>
              <li>Uploading malicious code, malware, or content that infringes on the rights of others.</li>
            </ul>

            <h3>8. AI Disclaimer</h3>
            <p>
              The Platform uses artificial intelligence (including Google Gemini and other models) to analyze tender documents, generate insights, assess risks, and estimate win probabilities. You acknowledge and agree that:
            </p>
            <ul>
              <li><strong>AI Outputs are informational only.</strong> They do not constitute legal advice, financial advice, procurement consulting, or any other form of professional guidance.</li>
              <li><strong>AI can produce errors.</strong> AI systems may generate inaccurate, incomplete, or misleading results. You should independently verify any AI Output before relying on it.</li>
              <li><strong>Win probability estimates are statistical approximations</strong>, not guarantees or predictions of actual outcomes. Many factors outside the Platform&apos;s analysis influence procurement decisions.</li>
              <li><strong>You are solely responsible for your decisions.</strong> Any decision to bid on, pursue, or rely on a tender opportunity is made at your own risk and discretion.</li>
              <li><strong>Winly does not guarantee the suitability</strong> of any matched tender for your specific business circumstances.</li>
            </ul>
            <p>
              Winly shall not be held liable for any loss, damage, or adverse outcome resulting from reliance on AI Outputs.
            </p>

            <h3>9. Intellectual Property</h3>
            <p>
              The Platform — including its design, user interface, algorithms, AI models, branding, logos, documentation, and all underlying software — is the exclusive intellectual property of Winly and is protected by copyright, trademark, and other intellectual property laws.
            </p>
            <p>
              Your Subscription grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Platform for your internal business purposes, subject to these Terms.
            </p>
            <p>
              You retain ownership of any data you provide to the Platform, such as your company profile information and uploaded documents. By providing this data, you grant Winly a limited license to process it for the purpose of delivering the Services.
            </p>
            <p>
              Public tender data aggregated by the Platform originates from publicly available government sources and remains in the public domain. Winly&apos;s intellectual property rights extend to the way this data is processed, enriched, organized, and presented — not to the underlying public records themselves.
            </p>

            <h3>10. Data and Privacy</h3>
            <p>
              We take your privacy seriously. Our collection, use, and protection of your personal data is governed by our <a href="/privacy">Privacy Policy</a>, which forms an integral part of these Terms.
            </p>
            <p>
              All personal data is processed in accordance with Regulation (EU) 2016/679 (General Data Protection Regulation — GDPR) and applicable Portuguese data protection legislation. You have the right to access, rectify, erase, restrict, or port your personal data as described in our Privacy Policy.
            </p>

            <h3>11. Third-Party Services</h3>
            <p>
              The Platform relies on third-party service providers to operate, including but not limited to:
            </p>
            <ul>
              <li><strong>Vercel</strong> — Frontend hosting and delivery.</li>
              <li><strong>Google Cloud Platform</strong> — Backend infrastructure, data processing, and AI services.</li>
              <li><strong>Supabase</strong> — Authentication and database services.</li>
              <li><strong>Lemon Squeezy</strong> — Payment processing and subscription management.</li>
              <li><strong>PostHog</strong> — Product analytics.</li>
            </ul>
            <p>
              Winly is not responsible or liable for any service interruption, data loss, or error caused by third-party providers. While we carefully select our partners, their services are subject to their own terms and availability commitments.
            </p>

            <h3>12. Service Availability</h3>
            <p>
              We make reasonable efforts to keep the Platform available and operational. However, we do not guarantee uninterrupted or error-free access. The Platform may be temporarily unavailable due to:
            </p>
            <ul>
              <li>Scheduled or emergency maintenance.</li>
              <li>Updates, improvements, or infrastructure changes.</li>
              <li>Third-party service outages beyond our control.</li>
              <li>Force majeure events.</li>
            </ul>
            <p>
              We reserve the right to modify, update, or discontinue any feature of the Platform at any time. For material changes that reduce functionality available under your current Subscription, we will provide reasonable advance notice.
            </p>

            <h3>13. Limitation of Liability</h3>
            <p>
              To the maximum extent permitted by applicable law:
            </p>
            <ul>
              <li>Winly shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, loss of revenue, loss of data, missed tender opportunities, or business interruption.</li>
              <li>Winly shall not be liable for any damages arising from inaccurate or incomplete tender data, AI errors, or missed matches.</li>
              <li>Winly&apos;s total aggregate liability to you for any claims arising under or in connection with these Terms shall not exceed the total fees you have paid to Winly during the twelve (12) months immediately preceding the event giving rise to the claim.</li>
              <li>For Users on the free Explorer tier, Winly&apos;s maximum aggregate liability shall not exceed fifty euros (&euro;50).</li>
            </ul>
            <p>
              Nothing in these Terms excludes or limits liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded under applicable EU or Portuguese law.
            </p>

            <h3>14. Account Suspension and Termination</h3>
            <p>
              Winly reserves the right to suspend or terminate your Account, without prior notice, if:
            </p>
            <ul>
              <li>You violate these Terms or any applicable law.</li>
              <li>Your use of the Platform poses a security risk or may harm other Users.</li>
              <li>Your Account has been inactive for an extended period (we will notify you before deleting inactive accounts).</li>
              <li>We are required to do so by law or a regulatory authority.</li>
            </ul>
            <p>
              You may delete your Account at any time through your Account settings or by contacting us at <a href="mailto:support.winly@winly.me">support.winly@winly.me</a>. Upon deletion, your personal data will be handled in accordance with our Privacy Policy and applicable data retention obligations.
            </p>

            <h3>15. Changes to These Terms</h3>
            <p>
              We may update these Terms from time to time to reflect changes in our Services, legal requirements, or business practices. When we make changes:
            </p>
            <ul>
              <li>We will provide at least 30 days&apos; advance notice by email to the address associated with your Account.</li>
              <li>The updated Terms will be posted on this page with a revised &quot;Last updated&quot; date.</li>
              <li>Your continued use of the Platform after the effective date of the changes constitutes your acceptance of the updated Terms.</li>
            </ul>
            <p>
              If you do not agree to the updated Terms, you must stop using the Platform and cancel your Subscription before the changes take effect.
            </p>

            <h3>16. Governing Law and Disputes</h3>
            <p>
              These Terms are governed by and construed in accordance with the laws of the Portuguese Republic and applicable European Union legislation.
            </p>
            <p>
              Any dispute arising from or in connection with these Terms shall be submitted to the exclusive jurisdiction of the courts of Lisbon, Portugal, unless you are a consumer residing in the EU, in which case you may also bring proceedings in the courts of your country of residence.
            </p>
            <p>
              As an EU consumer, you retain all mandatory consumer protection rights granted by the laws of your country of residence, and nothing in these Terms limits those rights.
            </p>
            <p>
              You may also use the European Commission&apos;s Online Dispute Resolution platform at <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/consumers/odr</a>.
            </p>

            <h3>17. Contact</h3>
            <p>
              If you have any questions, concerns, or requests regarding these Terms, please contact us:
            </p>
            <ul>
              <li><strong>Email:</strong> <a href="mailto:support.winly@winly.me">support.winly@winly.me</a></li>
              <li><strong>Address:</strong> Winly, Lda., Avenida da Liberdade, 110, 1250-146 Lisboa, Portugal</li>
            </ul>

            <div className="mt-8 pt-8 border-t border-zinc-100">
                <p className="text-sm text-zinc-500">
                    By using Winly, you confirm that you have read, understood, and agreed to these Terms and Conditions. If you have any questions, reach out to us at <a href="mailto:support.winly@winly.me" className="text-blue-600 hover:underline">support.winly@winly.me</a>.
                </p>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
