const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../../.env') });

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("❌ Missing Supabase credentials in .env");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

async function generateCpvData() {
  console.log("🔄 Fetching CPV codes from Supabase...");
  
  // Fetch all codes to filter locally (safer for format variations)
  let allCodes = [];
  let page = 0;
  const pageSize = 1000;
  
  while (true) {
    const { data, error } = await supabase
      .from('cpv_codes')
      .select('code, description, description_pt')
      .range(page * pageSize, (page + 1) * pageSize - 1);
      
    if (error) {
      console.error("Error fetching CPV codes:", error);
      process.exit(1);
    }
    
    if (data.length === 0) break;
    
    allCodes = [...allCodes, ...data];
    page++;
    process.stdout.write(`\rLoaded ${allCodes.length} codes...`);
  }
  
  console.log(`\n✅ Fetched ${allCodes.length} total codes.`);
  
  const divisions = [];
  const divisionMap = {};
  const divisionMapPt = {};

  allCodes.forEach(row => {
    // Clean code: 03000000-1 -> 03000000
    const cleanCode = row.code.replace(/[^0-9]/g, '').slice(0, 8);
    // Division prefix (2 digits)
    const divisionPrefix = cleanCode.substring(0, 2);
    
    // Check for Division (XX000000)
    if (cleanCode.endsWith('000000') && cleanCode.length === 8) {
        divisions.push({
            value: divisionPrefix,
            label: row.description,
            label_pt: row.description_pt,
            fullCode: cleanCode
        });
        
        divisionMap[divisionPrefix] = row.description;
        divisionMapPt[divisionPrefix] = row.description_pt || row.description;
    }
  });
  
  // Sort divisions by code
  divisions.sort((a, b) => a.value.localeCompare(b.value));
  
  // Construct content
  const parts = [];
  parts.push("// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY");
  parts.push("// Generated by scripts/generate_cpv_ts.js");
  parts.push("// Source: Supabase (cpv_codes table) - DIVISIONS ONLY");
  parts.push("");
  parts.push("// Map of 2-digit prefix to Division Name (EN)");
  parts.push("export const CPV_DIVISION_MAP: Record<string, string> = " + JSON.stringify(divisionMap, null, 2) + ";");
  parts.push("");
  parts.push("// Map of 2-digit prefix to Division Name (PT)");
  parts.push("export const CPV_DIVISION_MAP_PT: Record<string, string> = " + JSON.stringify(divisionMapPt, null, 2) + ";");
  parts.push("");
  parts.push("// Array for Dropdowns");
  parts.push("export const CPV_DIVISIONS = " + JSON.stringify(divisions, null, 2) + ";");
  parts.push("");
  parts.push("// For backward compatibility with some components");
  parts.push("export const CPV_CODES = CPV_DIVISIONS; "); 
  parts.push("");
  parts.push("export function getCpvDescription(cpvCode: string | null | undefined, locale: string = 'en'): string {");
  parts.push("    if (!cpvCode) return 'N/A';");
  parts.push("    ");
  parts.push("    // Clean code");
  parts.push("    const cleanCode = cpvCode.replace(/[^0-9]/g, '').slice(0, 8);");
  parts.push("    const division = cleanCode.substring(0, 2);");
  parts.push("    const map = locale === 'pt' ? CPV_DIVISION_MAP_PT : CPV_DIVISION_MAP;");
  parts.push("    ");
  parts.push("    // If it is a division root");
  parts.push("    if (cleanCode.endsWith('000000') && map[division]) {");
  parts.push("        return map[division];");
  parts.push("    }");
  parts.push("    ");
  parts.push("    // If we have the parent category");
  parts.push("    if (map[division]) {");
  parts.push("        return map[division] + (locale === 'pt' ? ' (Categoria)' : ' (Category)');");
  parts.push("    }");
  parts.push("    ");
  parts.push("    return (locale === 'pt' ? 'Setor Especializado (' : 'Specialized Sector (') + cpvCode + ')';");
  parts.push("}");

  const fileContent = parts.join("\n");

  const outputPath = path.resolve(__dirname, '../src/utils/cpv-data.ts');
  fs.writeFileSync(outputPath, fileContent);
  console.log(`✅ Wrote ${divisions.length} CPV divisions to ${outputPath}`);
}

generateCpvData();